# Site settings
title: BY Blog
SEOTitle: zeroGo | BY Blog
header-img: img/post-bg-desk.jpg
email: 1060056932@qq.com
description: "Every failure is leading towards success."
keyword: "BY, BY Blog, 张文锋的博客, 张文锋, zeroGo, 张武锋的博客, "
url: "https://zerogozhang.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/zeroGozhang/zeroGoZhang.github.io" # you code repository

# Sidebar settings
#sidebar: true                           # whether or not using Sidebar.
#sidebar-about-description: "Goals determine what you going to be!"
#sidebar-avatar: /img/about-BY-gentle1.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username: qiubaiying
zhihu_username: zeroGo
github_username: zeroGo
facebook_username: zeroGo
jianshu_username: zeroGo
#twitter_username: qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



#评论系统
#Disqus（https://disqus.com/）
#disqus_username:	zeroGo zhang

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: a0a1f4d83d1a081773e0                            #生成的clientID
  clientSecret: 52e4651524e6516beced6118110ad6b891d8eb81    #生成的clientSecret
  repo: zerogozhang.github.io    #仓库名称
  owner: zeroGozhang    #github用户名
  admin: zeroGozhang
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: e4341a252467d4354d767d7b4ea600de

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





## Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
#    {
#        title: "WY",
#        href: "http://zhengwuyang.com"
#    }
]
